### ISSUE TITLE
Mat able to launch emulator

### ISSUE THREAD

**Issue by enrauk** [Dannark/Android-Launcher-for-VSCode#1]
Hi,  I have managed to get a little further but I keep getting an error "unable to load emulator"

the results of emulator -list -avds are:
![image](https://user-images.githubusercontent.com/64270593/83746105-8101d280-a656-11ea-88a2-6461dbde9628.png)

my user variables are set as follows:
![image](https://user-images.githubusercontent.com/64270593/83746260-c0302380-a656-11ea-88ba-87f1c3f91b5d.png)
my path is set as follows:
![image](https://user-images.githubusercontent.com/64270593/83746393-ec4ba480-a656-11ea-875e-5c40a641ceab.png)

Thanks for the prompt response yesterday and for your help
Regards Enrico

**Comment by Dannark** [comment]
Hey Enrak! Thanks for your report. Your variables seams to be correct for that command. And there is actually a problem here not showing some messages that i will be fixing it today. :)

Please run the command `sdkmanager --list` on your terminal.

And tell me what it brings to you.

**Comment by Dannark** [comment]
I just noticed the correct command is `emulator -list-avds` not `emulator -list -avds`.

**Comment by enrauk** [comment]
Hi,

Using the correct emulator command works as expected
![image](https://user-images.githubusercontent.com/64270593/83805407-bda9ea00-a6a7-11ea-88d1-7056ec611600.png)

sdkmanager --list also works as expected
![image](https://user-images.githubusercontent.com/64270593/83805539-f944b400-a6a7-11ea-95cd-80c21eb231bb.png)

I have upgraded to v0.05 but am still getting the same error
![image](https://user-images.githubusercontent.com/64270593/83805702-458ff400-a6a8-11ea-8d5e-2755031dac80.png)

Thanks for your help on this
Regards
Enrico

**Comment by Dannark** [comment]
Great, we are getting there!

Finally, please run this command `emulator -avd Pixel_3a_API_29` and tell me the error it brings to you.

It's probably your Virtualization Setting, especially if you are using AMD. Like the google says: `Virtualization or SVM must be enabled in your computer's BIOS settings.`

So I recommend you two steps:

1. Enable the VT-x in your bios, [here](https://2nwiki.2n.cz/pages/viewpage.action?pageId=75202968) you can find some instructions in different brands

2. Enable the `Windows Hypevisor Platform` in your system, following the instructions [here](https://developer.android.com/studio/run/emulator-acceleration#vm-windows-whpx)
Actualy the name on my computer was a bit different, it is called `Hype-V` as I show in this image:
![image](https://user-images.githubusercontent.com/7622553/83811793-dbb82000-a690-11ea-9bee-142eb3119b75.png)

I also had to do these steps in order to launch the emulator on my windows.

**Comment by enrauk** [comment]
The error is
![image](https://user-images.githubusercontent.com/64270593/83825966-a3393600-a6d2-11ea-8441-86003fe86cfe.png)

**Comment by Dannark** [comment]
Please check this answer https://stackoverflow.com/a/52496987/2797044

`The cause was that the path to emulator had changed, so don't use ...../Android/Sdk/tools/emulator but instead ....../Android/Sdk/emulator/emulator`

This is how my variables are set:
![image](https://user-images.githubusercontent.com/7622553/83827081-d1f3e400-a6b3-11ea-8a7e-5f15b4c3fef8.png)

And i'm using lastest version of Android Studio.

**Comment by enrauk** [comment]
Hi, I have managed to get the emulator loading but am now getting an adb error (any idea how to fix this?), although I don't get the adb error when launching through your extension.  I don't know if that because your launcher supresses the message or whether it is because t resolves it.

![image](https://user-images.githubusercontent.com/64270593/83905572-cce97000-a759-11ea-8ba0-4f65ce48457f.png)

As well as setting the emulator path I had to move it to the top of the list of paths for the Android SDK and I had to turn on the Virtual Machines Platform as well as HyperV
![image](https://user-images.githubusercontent.com/64270593/83905792-323d6100-a75a-11ea-8f8e-f000d865bdb9.png)

Thanks once again for your help on this.  It is much appreciated.

Regards,
Enrico

**Comment by enrauk** [comment]
I managed to resolve the above error.  Thanks once again.  Regards, Enrico

**Comment by Dannark** [comment]
I'm really happy that you did it! And thanks for your review.
Good Luck!

**Comment by RISHABHSIDANA** [comment]
I'm not able to use this extension.Please @Dannark can you help

**Comment by Dannark** [comment]
@RISHABHSIDANA Sure but please, open an issue if more details about your problem, where did you get stuck?
